Repository RecyThing/RecyThing-Web, pull requests merged in 2023-12, with the labels that each got.

#89 feat(user-pagination): add pagination to manage user (#008)
  src/apis/APIUser.js
  src/pages/AdminRoot.jsx
  src/pages/ManageUser.jsx
  src/services/auth.service.js
  src/store/user/fetchUsersSlice.js
Labels: enhancement

#99 feat(401-handler): add condition when response is 401
  src/configs/axios/index.js
  src/routes/index.jsx
  src/services/auth.service.js
  src/utils/global/globalRoute.js
  src/utils/index.js
Labels: enhancement

#113 feat(api-integration): add api integration community (#021)
  src/apis/APICommunity.js
  src/apis/index.js
  src/components/modal/community/CommunityFormFields.jsx
  src/components/modal/community/CommunityFormSchema.js
  src/components/modal/community/ModalAddCommunity.jsx
  src/components/modal/community/ModalEditDetailCommunity.jsx
  src/components/modal/community/ModalViewDetailCommunity.jsx
  src/components/tables/community/TableCommunityList.jsx
  src/pages/Community.jsx
  src/store/community/createCommunitySlice.js
  src/store/community/deleteCommunitySlice.js
  src/store/community/fetchCommunitiesSlice.js
  src/store/community/fetchCommunitySlice.js
  src/store/community/index.js
  src/store/community/updateCommunitySlice.js
  src/store/index.js
Labels: enhancement

#116 feat(api-integration): add api integration for mission approval (#017)
  src/apis/APIApprovalMission.js
  src/apis/index.js
  src/components/modal/action-feedback/ModalApprove.jsx
  src/components/modal/action-feedback/ModalReject.jsx
  src/components/modal/mission-approval/ModalViewMissionApproval.jsx
  src/components/modal/mission-approval/TabButton.jsx
  src/components/modal/mission-approval/TabContent.jsx
  src/components/modal/transaction-list/ModalEditDetailTransaction.jsx
  src/components/tables/mission-approval/TableMissionApproval.jsx
  src/pages/MissionApproval.jsx
  src/store/approval-mission/fetchApprovalSlice.js
  src/store/approval-mission/fetchApprovalsSlice.js
  src/store/approval-mission/index.js
  src/store/approval-mission/updateApprovalSlice.js
  src/store/community/fetchCommunitySlice.js
  src/store/index.js
Labels: enhancement

#118 feat(dashboard-filter): Fix Align in ranking user, and typo in yearly filter
  src/components/content-article/AddArticle.jsx
  src/components/content-article/EditArticle.jsx
  src/components/dashboard/InfoCard.jsx
  src/components/dashboard/LineGraph.jsx
  src/components/dashboard/RankingUser.jsx
  src/components/modal/data-drop-point/ModalAddDataDropPoint.jsx
  src/components/tables/data-drop-point/TableDataDropPoint.jsx
  src/pages/Dashboard.jsx
Labels: enhancement

#122 feat(dashboard-filter): change info card status
  src/components/dashboard/InfoCard.jsx
  src/pages/Dashboard.jsx
Labels: enhancement

#124 refactor(user-detail): simplify code
  src/apis/APIUser.js
  src/components/modal/manage-user/DetailUserField.jsx
  src/components/modal/manage-user/ModalViewUserDetail.jsx
  src/components/navigation/dashboard/SearchBar.jsx
  src/components/tables/manage-user/TableUserList.jsx
  src/pages/ManageUser.jsx
  src/store/user/fetchUserSlice.js
  src/store/user/fetchUsersSlice.js
  src/store/user/index.js
  src/utils/format-number/formatWithCommas.js
  src/utils/format-number/index.js
  src/utils/index.js
Labels: refactor

#125 refactor(voucher-list): simplify code
  src/components/modal/action-feedback/ModalDelete.jsx
  src/components/modal/voucher-list/ModalAddVoucher.jsx
  src/components/modal/voucher-list/ModalEditVoucher.jsx
  src/components/modal/voucher-list/VoucherFormFields.jsx
  src/components/modal/voucher-list/VoucherFormSchema.js
  src/components/tables/manage-user/TableUserList.jsx
  src/components/tables/voucher-list/TableVoucherList.jsx
  src/pages/VoucherList.jsx
Labels: refactor

#126 refactor(data-reporting): simplify code
  src/components/modal/action-feedback/ModalApprove.jsx
  src/components/modal/action-feedback/ModalReject.jsx
  src/components/modal/data-reporting/DetailScaleReport.jsx
  src/components/modal/data-reporting/DetailTrashReport.jsx
  src/components/modal/data-reporting/ItemField.jsx
  src/components/modal/data-reporting/ModalRejectionReason.jsx
  src/components/modal/data-reporting/ModalViewImageReporting.jsx
  src/components/modal/data-reporting/ModalViewReportingApproval.jsx
  src/components/tables/base-table/TableCells.jsx
  src/components/tables/data-reporting/TableDataReporting.jsx
  src/pages/DataReporting.jsx
  src/store/report/fetchDataReportSlice.js
Labels: refactor

#129 prod(compression): add compression for production
  package-lock.json
  package.json
  vite.config.js
Labels: enhancement

#132 feat(dashboard-card): Change Dashboard card item to income
  src/components/content-article/ArticleCategory.jsx
  src/components/content-article/ArticleItem.jsx
  src/components/dashboard/InfoCard.jsx
  src/components/modal/content-article/ArticleDetail.jsx
  src/index.css
  src/pages/Dashboard.jsx
Labels: enhancement

#123 feat(detail-event-komunitas) : API Integration in detail event (#24)
  src/apis/APIEventCommunity.js
  src/apis/index.js
  src/components/inputs/input-date/DummyInput.jsx
  src/components/inputs/input-date/index.jsx
  src/components/modal/event-community/ButtonCopyLink.jsx
  src/components/modal/event-community/CommunityEditFormFields.jsx
  src/components/modal/event-community/CommunityEventFormSchema.js
  src/components/modal/event-community/CommunityFormFields.jsx
  src/components/modal/event-community/DetailEventField.jsx
  src/components/modal/event-community/EventCommunityFields.jsx
  src/components/modal/event-community/ModalAddEventCommunity.jsx
  src/components/modal/event-community/ModalEditCommunity.jsx
  src/components/modal/event-community/ModalEditEventCommunity.jsx
  src/components/modal/event-community/ModalViewDetailEvent.jsx
  src/components/modal/index.js
  src/components/tables/index.js
  src/components/tables/manage-event-community/TableManageEventCommunity.jsx
  src/pages/ManageEventCommunity.jsx
  src/store/event-community/createEventSlice.js
  src/store/event-community/deleteEventSlice.js
  src/store/event-community/fetchEventSlice.js
  src/store/event-community/fetchEventsSlice.js
  src/store/event-community/index.js
  src/store/event-community/updateEventSlice.js
  src/store/index.js
Labels: enhancement

#146 bugfix(add-modal): fix add modal wont close
  src/components/modal/voucher-list/ModalAddVoucher.jsx
Labels: bug

#147 bugfix(delete-modal): fix how delete modal loading in community
  src/components/tables/community/TableCommunityList.jsx
  src/pages/Community.jsx
Labels: bug

#150 refactor(scrollbar): modify the style of scrollbar
  src/index.css
Labels: refactor

#153 bugfix: fix bug on date picker
  src/components/inputs/input-date/index.jsx
  src/components/tables/rubbish-category/TableRubbishCategory.jsx
  src/pages/Community.jsx
  src/pages/DataReporting.jsx
  src/pages/TransactionList.jsx
Labels: bug
